name: Run Pytest on Push

on:
  push:
    branches:
      - main  # Change this if you use another branch

jobs:
  test:
    runs-on: windows-latest  # Use ubuntu-latest for Linux

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust to match your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: pytest --tb=short
